name: Aeon 3 n Village (gather-branch)

on:
  workflow_dispatch: # manual trigger ability
  schedule:
    # Run every day at 7:16 AM MY time, 11:16 PM UTC
    - cron: '16 23 * * *' 

jobs:
  setup:
    runs-on: windows-latest
    permissions:
      contents: write # Grant write permissions for pushing changes
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: gather-branch # Specify gather-branch directly for the primary checkout
          path: . # CHANGE: Checkout to the root of the runner's working directory      

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.10'

      - name: Download 7-Zip installer
        run: |
          Invoke-WebRequest -Uri "https://www.7-zip.org/a/7z2301-x64.exe" -OutFile "7zip_installer.exe"

      - name: Install 7-Zip silently
        run: |
          Start-Process -FilePath ".\7zip_installer.exe" -ArgumentList "/S" -Wait

      - name: Add 7-Zip to PATH
        run: |
          $env:Path += ";C:\Program Files\7-Zip"
          echo "PATH updated"
        
      - name: Display system information
        run: |
          echo "Windows version:"
          systeminfo
          echo "Python version"
          python -V
          echo "IP address"
          curl https://api.ipify.org
          

      - name: Set display resolution to 1920x1080
        run: powershell.exe -Command "Set-DisplayResolution -Width 1920 -Height 1080 -Force"
                       
      - name: Unzip .7z
        run: |
          & "C:\Program Files\7-Zip\7z.exe" x runner-src/gather_aeon_vill.7z -p${{ secrets.ZIP_PW }}

      - name: pip install
        run: pip install -r requirements_2.txt
          
      - name: Run scripts concurrently and wait
        shell: pwsh
        run: |
          $p1 = Start-Process -FilePath "python" -ArgumentList "aeon_cdp_args_032.py", "-c", "aeon-categories-3.txt", "-o", "aeon-out-part3.csv" -PassThru
          $p2 = Start-Process -FilePath "python" -ArgumentList "village_038_one_thread.py" -PassThru

          Write-Host "Scripts launched. Waiting for completion..."
          Wait-Process -Id $p1.Id
          Wait-Process -Id $p2.Id

          Write-Host "Scripts done."
          Write-Host "Error log:"
          Get-Content village_error_log.txt


      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Pull latest changes before push
        run: |
          git pull origin gather-branch --rebase
          git push origin gather-branch
         
      - name: Commit and push generated files
        run: |
          copy aeon-out-part3.csv raw_data/
          git add raw_data/aeon-out-part3.csv     
          cp village-gather.csv raw_data/
          git add raw_data/village-gather.csv          
          git commit -m "Automated: Add generated Aeon 3 and Village file" || echo "No changes to commit"
          git push origin gather-branch              
