name: Aeon flow 2b (aeon-branch)

on:
  workflow_dispatch: # manual trigger ability
  schedule:
    # Run every day at 7:14 AM MY time (11:14 PM UTC), evening
    - cron: '14 23 * * *' 

jobs:
  setup:
    runs-on: windows-2022
    permissions:
      contents: write # Grant write permissions for pushing changes
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: aeon-branch # Specify aeon-branch directly for the primary checkout
          path: . # CHANGE: Checkout to the root of the runner's working directory      

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.10'

      - name: Download 7-Zip installer
        run: |
          Invoke-WebRequest -Uri "https://www.7-zip.org/a/7z2301-x64.exe" -OutFile "7zip_installer.exe"

      - name: Install 7-Zip silently
        run: |
          Start-Process -FilePath ".\7zip_installer.exe" -ArgumentList "/S" -Wait

      - name: Add 7-Zip to PATH
        run: |
          $env:Path += ";C:\Program Files\7-Zip"
          echo "PATH updated"
        
      - name: Display system information
        run: |
          echo "Windows version:"
          systeminfo
          echo "Python version"
          python -V
          echo "IP address"
          curl https://ipinfo.io/ip
          curl https://api.ipify.org
          Write-Host $PSVersionTable.PSVersion          

      - name: Set display resolution to 1920x1080
        run: powershell.exe -Command "Set-DisplayResolution -Width 1920 -Height 1080 -Force"
                       
      - name: Unzip .7z
        run: |
          & "C:\Program Files\7-Zip\7z.exe" x runner-src/gather-aeon.7z -p${{ secrets.ZIP_PW }}

      - name: pip install
        run: pip install -r requirements.txt

      - name: Ensure log dirs exists (Windows)
        shell: pwsh
        run: |
          if (!(Test-Path "archived_logs")) {
            New-Item -ItemType Directory -Path "archived_logs"
          }
          if (!(Test-Path "latest_logs")) {
            New-Item -ItemType Directory -Path "latest_logs"
          }
          Write-Host "Created archived_logs: $(Test-Path 'archived_logs')"

      - name: Set permissions on log dirs
        shell: pwsh
        run: |
          $acl = Get-Acl "."
          Set-Acl "archived_logs" $acl
          Set-Acl "latest_logs" $acl

      - name: Run scripts concurrently (Windows)
        shell: cmd
        run: |
          start python aeon_cdp_args_033_proxy.py -c aeon-categories-3.txt -o aeon-out-part3.csv -p proxy1.txt
          start python aeon_cdp_args_032.py -c aeon-categories-2.txt -o aeon-out-part2.csv

      - name: Await completion
        shell: pwsh
        run: |
          Write-Host "Waiting for 9.5 minutes..."
          Start-Sleep -Seconds 570
      
          $maxWaitMinutes = 22
          $endTime = (Get-Date).AddMinutes($maxWaitMinutes)
          $loopCount = 0
      
          while ((Get-Date) -lt $endTime) {
            if (Test-Path "aeon-out-part2.csv" -PathType Leaf) {
              if (Test-Path "aeon-out-part3.csv" -PathType Leaf) {
                Write-Host "Both files found. Continuing..."
                exit 0
              }
            }
      
            $loopCount++
            Write-Host "Output files not found. Waiting for 1 minute ($loopCount of $maxWaitMinutes)."
            Start-Sleep -Seconds 60
          }
      
          Write-Host "Timeout: Aborting action after 31 minutes."
          exit 1
      
      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Pull latest changes before push
        run: |
          git pull origin aeon-branch --rebase
          git push origin aeon-branch
         
      - name: Commit and push generated files
        run: |
          copy aeon-out-part* raw_data/
          git add raw_data/aeon-out-part2.csv     
          git add raw_data/aeon-out-part3.csv     
          git commit -m "Automated: Add generated Aeon 2 files" || echo "No changes to commit"
          git push origin aeon-branch              
