name: Aeon flow 1b (aeon-branch)

on:
  workflow_dispatch: # manual trigger ability
  schedule:
    # Run every day at 7:13 AM MY time 11:13 PM UTC), evening
    - cron: '13 23 * * *'

jobs:
  setup:
    runs-on: windows-latest
    permissions:
      contents: write # Grant write permissions for pushing changes
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: aeon-branch # Specify aeon-branch directly for the primary checkout
          path: . # CHANGE: Checkout to the root of the runner's working directory      

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.10'

      - name: Download 7-Zip installer
        run: |
          Invoke-WebRequest -Uri "https://www.7-zip.org/a/7z2301-x64.exe" -OutFile "7zip_installer.exe"

      - name: Install 7-Zip silently
        run: |
          Start-Process -FilePath ".\7zip_installer.exe" -ArgumentList "/S" -Wait

      - name: Add 7-Zip to PATH
        run: |
          $env:Path += ";C:\Program Files\7-Zip"
          echo "PATH updated"
        
      - name: Display system information
        run: |
          echo "Windows version:"
          systeminfo
          echo "Python version"
          python -V
          echo "IP address"
          curl https://ipinfo.io/ip
          
      - name: Set display resolution to 1920x1080
        run: powershell.exe -Command "Set-DisplayResolution -Width 1920 -Height 1080 -Force"
                       
      - name: Unzip .7z
        run: |
          & "C:\Program Files\7-Zip\7z.exe" x runner-src/gather-aeon.7z -p${{ secrets.ZIP_PW }}

      - name: pip install
        run: pip install -r requirements.txt
        
      - name: Ensure archived_logs dir exists
        shell: pwsh
        run: |
          if (!(Test-Path "archived_logs")) {
            New-Item -ItemType Directory -Path "archived_logs"
          }
          if (!(Test-Path "latest_logs")) {
            New-Item -ItemType Directory -Path "latest_logs"
          }   

      - name: Run script and validate output with retry
        shell: pwsh
        run: |
          function Check-OutputFile {
            param (
              [string]$FilePath,
              [int]$MinSize
            )
      
            if (-Not (Test-Path $FilePath)) {
              Write-Output "** Output file does not exist **"
              return $false
            }
      
            $filesize = (Get-Item $FilePath).Length
            if ($filesize -lt $MinSize) {
              Write-Output "** Output file is too small ($filesize bytes) **"
              return $false
            }
      
            Write-Output "Validation passed: output file seems OK."
            return $true
          }
      
          Write-Output "=== First attempt ==="
          python -u aeon_cdp_args_032.py -c aeon-categories-1.txt -o aeon-out-part1.csv
          $isValid = Check-OutputFile -FilePath "aeon-out-part1.csv" -MinSize 1500
      
          if (-Not $isValid) {
            Write-Output "Initial output file check failed. Retrying after 15 seconds..."
            Start-Sleep -Seconds 15
      
            Write-Output "=== Second attempt ==="
            python -u aeon_cdp_args_032.py -c aeon-categories-1.txt -o aeon-out-part1.csv
            $isValid = Check-OutputFile -FilePath "aeon-out-part1.csv" -MinSize 1500
      
            if (-Not $isValid) {
              Write-Error "** Retry failed. Aborting. **"
              exit 1
            }
          }

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Pull latest changes before push
        run: |
          git pull origin aeon-branch --rebase
          git push origin aeon-branch
         
      - name: Commit and push generated files
        run: |
          copy aeon-out-part1.csv raw_data/
          git add raw_data/aeon-out-part1.csv         
          git commit -m "Automated: Add generated Aeon file" || echo "No changes to commit"
          git push origin aeon-branch              
