name: Village Workflow (Gather-branch)

on:
  workflow_dispatch: # manual trigger ability
  schedule:
    # Run every day at 7:16 AM MY time, 11:16 PM UTC
    - cron: '16 23 * * *' 

jobs:
  setup:
    runs-on: ubuntu-24.04
    permissions:
      contents: write # Grant write permissions for pushing changes
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: gather-branch # Specify gather-branch directly for the primary checkout
          path: . # CHANGE: Checkout to the root of the runner's working directory      
        
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.10'       
    
      - name: Display system information
        run: |
          echo "Ubuntu version:"
          lsb_release -a
          echo "Python version"
          python -V
          
      - name: Update package lists
        run: |
          sudo apt update
          apt list --upgradable        
        
      - name: Install basic utilities and 7-zip
        run: |
          sudo apt-get install -y \
            build-essential \
            python3-problem-report \
            linux-tools-common \
            linux-libc-dev \
            p7zip-full
              
      - name: Unzip gather-village.7z
        run: |
          7z x runner-src/gather-village.7z -p${{ secrets.ZIP_PW }}

      - name: pip install
        run: pip install -r requirements.txt
          
      - name: Run script
        run: |
          echo "running script"
          python village_scrape_036.py
          echo "Error log:"
          cat village_error_log.txt  
 
      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Pull latest changes before push
        run: |
          git pull origin gather-branch --rebase
          git push origin gather-branch
    
      - name: Commit and push generated files
        run: |
          mkdir -p raw_data
          cp village-gather.csv raw_data/
          git add raw_data/village-gather.csv
          git commit -m "Automated: Add generated Village files" || echo "No changes to commit"
          git push origin gather-branch      
