name: Jaya-Subang flow (gather-branch)

on:
  workflow_dispatch: # manual trigger ability
  schedule:
    # Run every day at 7:16 AM MY time, 11:16 PM UTC
    - cron: '16 23 * * *'

jobs:
  setup:
    runs-on: ubuntu-24.04
    permissions:
      contents: write # Grant write permissions for pushing changes
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: gather-branch # Specify gather-branch directly for the primary checkout
          path: . # CHANGE: Checkout to the root of the runner's working directory      
        
      - name: Display system information
        run: |
          echo "Ubuntu version:"
          lsb_release -a
          echo "Python version"
          python -V
          echo "IP address"
          curl --no-progress-meter https://ipinfo.io/ip
          
      - name: Update package lists
        run: |
          sudo apt update
          apt list --upgradable        
        
      - name: Install basic utilities and 7-zip
        run: |
          sudo apt-get install -y \
            build-essential \
            python3-problem-report \
            linux-tools-common \
            linux-libc-dev \
            p7zip-full
              
      - name: Unzip gather-jaya.7z
        run: |
          7z x runner-src/gather-jaya.7z -p${{ secrets.ZIP_PW }}

      - name: pip install
        run: pip install -r requirements.txt
          
      - name: Run script
        run: |
          echo "Install playwright chromium"
          python -m playwright install --with-deps --only-shell > /dev/null
          echo "running scripts"
          python jaya_pwright_2025_010_one_thread_arg.py -s jaya_subang_settings_1.json &
          sleep 1
          python jaya_pwright_2025_010_one_thread_arg.py -s jaya_subang_settings_2.json
          wait
          echo "Scripts done."

      - name: Validate output file
        run: |
          FILES=("jaya_subang_one_thread_1.csv" "jaya_subang_one_thread_2.csv")
          for FILE in "${FILES[@]}"; do
            echo "Checking if $FILE exists and is larger than 100 KB..."
            if [ ! -f "$FILE" ]; then
              echo "❌ File does not exist: $FILE"
              exit 1
            fi
            FILESIZE=$(stat -c%s "$FILE")
            if [ "$FILESIZE" -lt 102400 ]; then
              echo "❌ File size is too small: ${FILESIZE} bytes"
              exit 1
            fi
            echo "✅ File exists and is larger than 100 KB: ${FILESIZE} bytes"
          done
          echo "🎉 All files passed validation"

      - name: Run processing script
        run: |
          echo "running processing script"
          python jaya_subang_fixer_01.py
 
      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Pull latest changes before push
        run: |
          git pull origin gather-branch --rebase
    
      - name: Commit and push generated files
        run: |
          mkdir -p raw_data
          cp jaya_subang_one* raw_data/
          cp jaya_subang-output* raw_data/
          git add raw_data/jaya_subang_one*
          git add raw_data/jaya_subang-output*
          git commit -m "Automated: Add generated Jaya Subang files" || echo "No changes to commit"
          git push origin gather-branch      
