name: Manual test

on:
  workflow_dispatch: # manual trigger ability

jobs:
  setup:
    runs-on: windows-latest
    permissions:
      contents: write # Grant write permissions for pushing changes
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: aeon-branch # Specify branch directly for the primary checkout
          path: . # CHANGE: Checkout to the root of the runner's working directory      

         
      - name: Display system information
        run: |
          echo "Windows version:"
          systeminfo
          echo "Python version"
          python -V

      - name: Pull latest changes before push
        run: |
          git pull origin aeon-branch --rebase
          git push origin aeon-branch

      - name: Check commit timestamps and run aeon-concat.py if recent
        shell: bash
        run: |
          # git fetch origin aeon-branch
          # git checkout aeon-branch

          threshold=$(date -d '1 hour ago' +%s)
          run_script=false

          for file in raw_data/aeon-out-part{1..4}.csv; do
            if git ls-tree -r HEAD --name-only | grep -q "$file"; then
              commit_time=$(git log -1 --format="%ct" -- "$file")
              echo "$file last commit timestamp: $commit_time"
              if [ "$commit_time" -gt "$threshold" ]; then
                run_script=true
              fi
            else
              echo "$file not found in aeon-branch"
            fi
          done

          if [ "$run_script" = true ]; then
            echo "Recent changes detected. Running aeon-concat.py..."
            python aeon-concat.py
          else
            echo "No recent changes. Skipping aeon-concat.py."
          fi
